### ISSUE TITLE
Improve heading and Tamplets

### ISSUE THREAD

**Issue by Mayank1170** [FOSS-Community/progress-tracker#330]
## Overview
Improve heading and cards of website according to you
## Description

Progress Tracker made with python, it tracks the progress of the members of FOSS-community.

## Expected outcomes

Make heading of website visible using perfect color combination and make cards more attractive.
## Skills

HTML, CSS, JavaScript.
## Possible mentors

[Akshat Sharma](https://github.com/akshatcoder-hash)

## Expected project size

1 hours.

## Difficulty

Easy

**Comment by GJS2162** [comment]
> # #330
> ### I have learned basics of HTML and CSS
> ### Problem : Background and Template
> ### 9 - 15 September
@akshatcoder-hash

**Comment by Ujjwal-soni98** [comment]
PROBLEM: improve the heading and templates .
I currently deal with front-end section of the websites.I have good idea about HTML and CSS also a handful of knowledge about javascript.learning phase in javascript and seeking to learn back-end and then i will dive into the full-stack development of websites.

I will try to solve this issue sooner possible.
I wil first change the website's heading so that it look attractive to the user and then make the templates creatively designed.
@akshatcoder-hash

**Comment by adityyaa-10** [comment]
Improve Heading and Templates 

## About me 
I am Aditya Pandey, I am learning web development for like more than one and a half months. I have had my hands dirty on HTML, CSS and Javascript, till now.
Apart from that, I know C and C++ as well. 

## Issue
Improve Heading and Templates 

## Proposal
To Improve heading

## Timeline
11th September - 12th September

## Commitments
I'll try to submit it as soon as possible.

**Comment by akshatcoder-hash** [comment]
@GJS2162 Good work!
